### ISSUE TITLE
Encourage workflow with different pipelines

### ISSUE THREAD

**Issue by ashleve** [ashleve/lightning-hydra-template#106]
- add `#Pipelines` to readme
- add branch with
    - `test.py` pipeline
    - `k-fold.py` pipeline

Related to #103

**Comment by LuoXin-s** [comment]
@hobogalaxy Hi!
Think you for your continuous work, and I almost finished my reimplementation to liif use this template (for code component, now the documentation is poor). You can check [here](https://github.com/LuoXin-s/liif-lightning-hydra) to see if there are any good or not good style practice.

**Comment by hobogalaxy** [comment]
@LuoXin-s that's awesome.

I think It's better to have parameters in model and datamodule specified explicitly instead of relying or `ModuleName(*args, **kwargs)` - this is how it's currently implemented in the template mnist example but I will be changing that, since not specyfing params makes it difficult to reuse modules across different projects. 

Btw. you're welcome to post here any project you like but please do it in separate issues or in [discussions](https://github.com/hobogalaxy/lightning-hydra-template/discussions)
