### ISSUE TITLE
How to hyperparameter search the seed defind in config yaml file?

### ISSUE THREAD

**Issue by zhiyuanpeng** [ashleve/lightning-hydra-template#158]
I would like to use optune_sweeper to search a good seed defined in config yaml file. optune_sweeper can search parameters defined in modules, but for seed, how to search it? Thanks.

**Comment by ashleve** [comment]
Simply add it to `search_space` in `mnist_optuna.yaml`:
```yaml
search_space:
  +seed:
      type: int
      low: 1
      high: 10000
```
The "+" is only needed if seed is not already declared in config.

Alternatively you can do it with just command: 
```bash
python run.py -m hparams_search=mnist_optuna '+seed=interval(0, 10000)'
```

Would also recommend to replace the TPESampler in the config with random sampler, since I don't think it makes sense to use bayesian search for the seed

**Comment by zhiyuanpeng** [comment]
I see, thank you very much!
