### ISSUE TITLE
How to save Optuna's best hyperparameters

### ISSUE THREAD

**Issue by elisim** [ashleve/lightning-hydra-template#167]
Hi @ashleve,

Thank you for the great work.
I used the hparams search example in your template for my code, and successfully got:

![image](https://user-images.githubusercontent.com/17675462/131307519-21d00b0c-717f-4b44-821f-6798a8905b6f.png)

My question is, how can I save those params and best metric to a file, using your template?
I couldn't found an example for that.

Thanks,
Eli

**Comment by ashleve** [comment]
Hi @elisim,

I don't think this is possible since this behaviour is controlled by hydra optuna plugin - you would probably need to fork the plugin and modify it.

I usually get the best parameters through either logger (e.g. sort by best accuracy in wandb) or by [loading optuna study object from database](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.load_study.html).

Also, the two lines you showed should also be visible in the file with terminal logs generated by hydra.

**Comment by elisim** [comment]
Hi @ashleve,

Thank you for your answer.

> Also, the two lines you showed should also be visible in the file with terminal logs generated by hydra.

Great, I found the optimization results file under `multirun` folder. From my code:

![image](https://user-images.githubusercontent.com/17675462/131466365-ac30008a-ae4f-4e5a-9ffb-2b8ae7272e5b.png)

I think it might be helpful to add docs about it in the template 🙂

Thank you

**Comment by elisim** [comment]
BTW, I added docs about it also in Hydra's repo: https://github.com/facebookresearch/hydra/pull/1804

**Comment by 2533245542** [comment]
Hi,

I completed a hyperparameter sweep using Optuna and wants to use its optuna-dashboard to create a visualization, which is based on the database file created during a Optuna sweep. However, I could not find the database file. I did find the optimization_results.yaml though. Do you know where is it stored?
