### ISSUE TITLE
Is it possible to the K-Fold validation?

### ISSUE THREAD

**Issue by Mushtaqml** [ashleve/lightning-hydra-template#196]
Hi!

Thanks a lot for this amazing template and project. 

I was curious to know that can we do K-Fold cross validation using Pytorch Lightning with Hydra?. 

Thank You

**Comment by ashleve** [comment]
@Mushtaqml Recently there has been added new loop functionality to pytorch lightning which enables kfold cross validation, see the official example:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/loop_examples/kfold.py

**Comment by Mushtaqml** [comment]
I just came here to post about it @ashleve :), #coincidence Thanks a lot. I am checking it, hopefully we will be able to integrate it into this template too.

**Comment by EklavyaFCB** [comment]
A k-fold cross validation framework integration in this repository would be very much appreciated. 

Dunno how much your stance has changed since #204, but if lightning 2.0 has a way of implementing this, then it should be considered. It's the only real missing element imo to use this repository for academic research level R&D.
