### ISSUE TITLE
Why use val/acc_best for hyperparameter search in the MNIST example?

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#220]
I am not sure if I understand everything correctly but here is my thought.

The wandb only checkpoints the models based on val/acc so even if the hyperparameter search finds the best hyperparameter based on val/acc_best, there is not a way to get the model back. 

Should the hyperparameter search use val/acc instead such that we will find the best hyperparameter as well as a checkpointed model associated with it?

**Comment by ashleve** [comment]
Hyperparameter search and checkpointing doesn't have anything to do with wandb. It's the role of Optuna and CheckpointCallback.

Checkpoint callback by default always saves the best model (as `epoch_x.ckpt`) and last model (as `last.ckpt`). So you should be able to always find the right model in the logs folder.

If you use `val/acc` for hyperparameter search, it will only take into consideration the last model saved during each run (instead of the best model saved during each run). This of course might make sense in some use cases and it's up to you if you want to make it work like that.
