### ISSUE TITLE
cannot find Optuna's hyperparameter search storage file

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#224]
Hi,

I completed a hyperparameter sweep using Optuna and wants to use its optuna-dashboard to create a visualization, which is based on the database file created during a Optuna sweep. However, I could not find the database file. I did find the optimization_results.yaml though. Do you know where is it stored?

Also, would it be better to store to hyparameter sweep's own config as well in the multirun/ folder? Currently it only has the runs and the optimization_result.yaml

**Comment by ashleve** [comment]
Hi,
you can [see here that by default storage is set to null](https://github.com/ashleve/lightning-hydra-template/blob/0feda07965420791220f93b4841a6bbab081c313/configs/hparams_search/mnist_optuna.yaml#L18-L19). I've never used this feature before so I don't know how it should be configured.

As for storing the sweep config, I think it might not be possible to access it through code during the sweep execution due to the way Hydra works. If you want you can propose it as a feature on the Hydra repo.

**Comment by zf223669** [comment]
unfortunately, when I set the storage to my mysql database and run the project, It just stayed there and did not run, although it created some of the tables in the database, there is nothing in the tables...
