### ISSUE TITLE
How to debug my code step-by-step when use hparams_search?

### ISSUE THREAD

**Issue by yipliu** [ashleve/lightning-hydra-template#236]
Hi,

After I added the hparams_search in my own code,  I got the following error
```python
hydra_plugins/hydra_optuna_sweeper/_impl.py", line 219, in sweep
    values = [float(ret.return_value)]
ValueError: Return value must be float-castable. Got 'None'.
```
Therefore, I set **hparams_search: mnist_optuna.yaml** parameter in **config.yaml** to execute the debug step in VSCODE. But my code does not enter hparams_search mode.

Can you help me out with this error?

**Comment by ashleve** [comment]
Hi @yipliu, it seems like there might be `None` or `null` as one of the choices in hyperparameter search space? 

I think it might not be possible to do debugging for hydra multirun since it requires to run script with `-m` option enabled, for example:
```
python run.py -m datamodule.batch_size=32,64,128
```

Debugging multiruns is probably a question for hydra developers, you could try asking here:
https://github.com/facebookresearch/hydra

**Comment by yipliu** [comment]
Hi @ashleve , I try my best to find that **ret.return_value** is a tensor, but I have no idea why my code get **None** value

**Comment by ashleve** [comment]
@yipliu This is probably due to incorrect name of the metric used for optimization:
https://github.com/ashleve/lightning-hydra-template/blob/8b62eef9d0d9c863e88c0992595688d6289d954f/configs/hparams_search/mnist_optuna.yaml#L8-L11

**Comment by yipliu** [comment]
**WOW** That's right! Thank you!
