### ISSUE TITLE
Why use different metrics for train, val and test?

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#239]
After using this template for quite some time, I still don't know why `mnist_model.py` used different Accuracy instance  for train, test and val. It seems to me that using a unversial one would also ensure a proper reduction over epoch, as long as the values are logged?

<img width="585" alt="image" src="https://user-images.githubusercontent.com/28517073/147862933-591d0118-1498-48e0-a59a-7bc951cf48ac.png">

**Comment by ashleve** [comment]
Torchmetrics keep their history and have the following methods:
`metric.compute()` - for `Accuracy`, this would compute average based on all records.
`metric.reset()` - this simply resets the history. 

Say you want to access avg epoch train accuracy at the end of the training epoch:
```python
def training_epoch_end(self, outputs: List[Any]):
    epoch_train_acc = self.train_acc.compute()
```    
If you instead used single accuracy object for train, val and test, your average would be computed based on all of them, which would be incorrect and you wouldn't even detect your mistake.
 
When using `self.log("train/acc", acc, on_epoch=True)`, the lighting averages logged results by itself (without using torchmetrics methods I think). You can set reduction strategy by yourself with `self.log(...,  reduce_fx="mean")`. So in the simple example from the template, multiple metric objects for train,val test are not really necessary, but I would still advise to use them every time, since it's very easy to make undetectable mistakes. 

I'm also not sure if the metrics are computed correctly without multiple objects, when using multiple GPUs.

Also, remember that different torchmetrics have their special reduction strategies.

**Comment by yipliu** [comment]
How about using **TorchMetrics** instead? [doc](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html)
