### ISSUE TITLE
Issue when run "python train.py" demo 

### ISSUE THREAD

**Issue by Luxios22** [ashleve/lightning-hydra-template#274]
Traceback (most recent call last):
  File "train.py", line 22, in main
    return train(config)
  File "/src/training_pipeline.py", line 74, in train
    utils.log_hyperparameters(
  File "/opt/conda/envs/hydra/lib/python3.8/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/src/utils/__init__.py", line 142, in log_hyperparameters
    trainer.logger.log_hyperparams(hparams)
AttributeError: 'NoneType' object has no attribute 'log_hyperparams'

**Comment by ashleve** [comment]
@Luxios22 Thanks! Looks like after recent lightning release there's a need to verify that logger is set before logging hyperparameters. I added the verification with this PR: https://github.com/ashleve/lightning-hydra-template/pull/275

**Comment by shivam13juna** [comment]
@ashleve  this issue is still persisting, 
as mentioned on pytorch-lightning [logging](https://pytorch-lightning.readthedocs.io/en/latest/extensions/logging.html#logging-hyperparameters)

I specified 
`self.logger.log_hyperparams(self.hparams, {"hp/precision": 0, "hp/recall": 0, "hp/f1_score": 0})`

and get the same error 

AttributeError: 'NoneType' object has no attribute 'log_hyperparams'

**Comment by ashleve** [comment]
@shivam13juna I think this is expected behavior in lightning when no logger is used. Does it work for you if you attach the logger? If so then it's not an issue, you're supposed to check if `self.logger` exists before logging hyperparameters
