### ISSUE TITLE
New repo has breaks on github CI

### ISSUE THREAD

**Issue by turian** [ashleve/lightning-hydra-template#416]
This is a freshly cloned and pushed repo.

```
Run pytest -v
ImportError while loading conftest 'D:\a\inverse-audio-synthesis\inverse-audio-synthesis\tests\conftest.py'.
tests\conftest.py:1: in <module>
    import pyrootutils
E   ModuleNotFoundError: No module named 'pyrootutils'
Error: Process completed with exit code 1.
```

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/65918/184924694-767b2901-c44e-45a2-98ae-cbccefeca729.png">

**Comment by ashleve** [comment]
Thank you, this was caused by the `sh` package crashing during installation of requirements on windows, which made the `pyrootutils` package not install at all. 

For I commented out the `sh` dependency 
https://github.com/ashleve/lightning-hydra-template/blob/8987b23b7f991a3de3f043058abd7ba4f63ea13f/requirements.txt#L23

(`sh` is only needed in some tests, if it's not available the tests are skipped)
