### ISSUE TITLE
According to hydra documentation config names should not have .yaml extension

### ISSUE THREAD

**Issue by yermandy** [ashleve/lightning-hydra-template#420]
Hello. Taken from the official [documentation](https://hydra.cc/docs/advanced/defaults_list/) of Hydra 1.2:

> CONFIG_NAME: The name of a config, without the file system extension. e.g. mysql and not mysql.yaml.

https://github.com/ashleve/lightning-hydra-template/blob/5034fca4e59dd3b1dff4797cb313886ee4daba54/configs/train.yaml#L5-L14

There are more places with this inconsistency

**Comment by ashleve** [comment]
@yermandy Thank you for pointing this out! Sure, we can change this.

As far as I'm aware it doesn't affect functionality.

The reason for attaching the `.yaml` extension was to make it more clear what is happening for new users. 

I remember on my first contact with hydra, I didn't grasp immediately that the defaults list elements were referring to yaml files from other subfolders. Since the template purpose is also educational, attaching the extensions felt like it makes it more explicit. Making things more explicit for educational purpose was kind of a design principle behind this project.

That being said, if this is a standard recommended by hydra then we should probably comply with it.
