### ISSUE TITLE
What happended to the WatchModel callback?

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#431]
I have been using this template for quite some time but haven't been catching up the latest update. 

I just saw that this thing is gone? Just want to know what happened recently. Was it provided by pytorch-lightening itself already? 

If so I can update my copy accordingly.
<img width="247" alt="image" src="https://user-images.githubusercontent.com/28517073/186544816-6a20a910-80b2-4239-b6b2-71f1e8cf53b9.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/28517073/186544833-bf679f3d-3eca-4e39-82b7-8e511a9312d1.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/28517073/186544700-a7afc306-36e9-402e-8f76-242cf252585b.png">

**Comment by ashleve** [comment]
The callbacks are still available at [wandb-callbacks branch](https://github.com/ashleve/lightning-hydra-template/tree/wandb-callbacks), but they're not maintained so I can't ensure they're all still working, you might need to do some fixes.

The reason for removal was to make the template logger-agnostic instead of focusing on wandb.
