### ISSUE TITLE
`train.log` doesn't show training progress bar

### ISSUE THREAD

**Issue by bomcon123456** [ashleve/lightning-hydra-template#467]
Awesome project honestly! I'm using your project right now but having some issues while training with SLURM, since I can't see the terminal of the scheduled nodes, I can only check `train.log` or `slurm.log`; but both of those log doesn't show the training progress bar (stop at `Start training` or some DDP warnings); but there are still logs on tensorboard and new ckpts.
I've tried to disable colorlogs too but it still doesn't show up.
![image](https://user-images.githubusercontent.com/20278911/200887829-9652c15f-c4c0-4fc7-8dac-19e31e2ae9f2.png)

**Comment by eddiecong** [comment]
Not sure if it is this problem, but did you set False on the argument prog_bar in the log function?

I think a better way to distinguish if it's an environmental issue is to have a quick run on the MNIST classification template provided in the experiment folder and see if there is a progress bar showing up.

Could check this cmd:
python src/train.py experiment=example.yaml

**Comment by eddiecong** [comment]
Not sure if it is this problem, but did you set False on the argument prog_bar in the log function?

I think a better way to distinguish if it's an environmental issue is to have a quick run on the MNIST classification template provided in the experiment folder and see if there is a progress bar showing up.

Could check this cmd:
python src/train.py experiment=example.yaml

Reference Link:
https://github.com/ashleve/lightning-hydra-template#:~:text=chosen%20experiment%20config%3A-,python%20src/train.py%20experiment%3Dexperiment_name.yaml,-Experiment%20design

**Comment by ashleve** [comment]
I think Lightning intentionally doesn't treat progress bar as logging messages, since it's a continuous process intended for terminal.

For monitoring progress in real time you should use a dedicated logger like tensorboard.

Closing this for now. Feel free to reopen if you have any questions

**Comment by snknitin** [comment]
I'm facing the same issue from a clean run of the mnist in this repo without any changes. No progress bar, no epochs being displayed and they don't show up in logs too

**Comment by snknitin** [comment]
> I think a better way to distinguish if it's an environmental issue is to have a quick run on the MNIST classification template provided in the experiment folder and see if there is a progress bar showing up.

I ran the MNIST as is. The RichProgressBar doesn't show up for epochs at all. Only if i do a Keyboard Interrupt, it then shows up on some random epoch it was in. TQDM shows up for each epoch. Any idea why or how to fix it. It should be replicable since there are no changes. It's just not running or showing up or visible or present in the log files. Very difficult to understand training with this behavior. Atleast the RichProgressBar has a leave argument to print each epoch but it isn't visible in the terminal at all. I even did the Pycharm specific "Emulate as terminal" configuration for Rich but still nothing. Not sure why no one brought it up yet or if something wrong on my end . Can you please try it out once in a fresh copy of the latest mnist run? @ashleve
