### ISSUE TITLE
Hydra configs not included in python packaging

### ISSUE THREAD

**Issue by gokul-pv** [ashleve/lightning-hydra-template#525]
Hi there,

I have found that the hydra config files are not included in the python packages created by the setuptools. It would be great if you could also include configs folder in packaging, so that the code can be installed through pip and working.

**Comment by ashleve** [comment]
Thank you for the suggestion.

According to [this page](https://hydra.cc/docs/advanced/app_packaging/) from hydra docs, I think you only need to move the `config` inside `src`. As far as I'm aware, this doesn't require any more refactoring of the template apart from changing the path to config folder in each entry file (`train.py`, `eval.py`).

We could refactor the template to have configs in src folder by default. I'm not sure if I like it, will need to think more if there are any disadvantages

**Comment by gokul-pv** [comment]
Thank you @ashleve 

Perhaps, according to this [page ](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data) we could add `configs` folder to python package by setting `include_package_data` to True in setup function and add `MANIFEST.in` file. This way we do not have to refactor the template.

```
# An example for MANIFEST.in file 

include .project-root
include configs/*.yaml
include configs/**/*.yaml
```

Let me know your thoughts. Thank you

**Comment by ashleve** [comment]
@gokul-pv Thank you, I learned something new.

I did some tests and it turns out we can include the `configs/` folder in the package by simply adding a `__init__.py` file to it. I also tried the setup trough `MANIFEST.in` (without adding `__init__.py`), but have not succideed (perhaps the included files still need to be in a subfolder of `src`?).

I don't see a reason for not adding this file to the template so here's the relevant PR: https://github.com/ashleve/lightning-hydra-template/pull/539
